export const STARGAZERS_FETCH = 'STARGAZERS_FETCH';
export const STARGAZERS_STOP_FETCH = 'STARGAZERS_STOP_FETCH';
export const STARGAZERS_REQUEST = 'STARGAZERS_REQUEST';
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
